// <auto-generated />
using System;
using CompanyData.Shared.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyData.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyData.Shared.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43738933-acf0-4479-8624-0ef1bec0383d"),
                            CreatedBy = "HR",
                            ModifiedBy = "HR",
                            Name = "Engineering & Product",
                            Supervisor = "paul@company.com"
                        },
                        new
                        {
                            Id = new Guid("6c7e9c5d-89ae-43d9-8f19-feb71af65e8f"),
                            CreatedBy = "HR",
                            ModifiedBy = "HR",
                            Name = "Marketing & Sales",
                            Supervisor = "Adex@company.com"
                        });
                });

            modelBuilder.Entity("CompanyData.Shared.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WagesInDollar")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("acc627bb-7733-4e13-876e-7d49a3838c12"),
                            Address = "8,Mesa Road",
                            City = "Houston",
                            CreatedBy = "HR",
                            DeletedBy = "HR",
                            DepartmentId = new Guid("43738933-acf0-4479-8624-0ef1bec0383d"),
                            Email = "paul@company.com",
                            FirstName = "Isaac",
                            IsDeleted = false,
                            JobRole = "Tech Lead",
                            LastName = "Paul",
                            ModifiedBy = "HR",
                            PhoneNumber = "+1312754448",
                            State = "Texas",
                            WagesInDollar = 4500.0
                        },
                        new
                        {
                            Id = new Guid("d17d52bd-9178-41d1-b399-705f6b7899b9"),
                            Address = "12,ogunnaike street GRA",
                            City = "Ikeja",
                            CreatedBy = "HR",
                            DeletedBy = "HR",
                            DepartmentId = new Guid("6c7e9c5d-89ae-43d9-8f19-feb71af65e8f"),
                            Email = "cherry@company.com",
                            FirstName = "Cherri",
                            IsDeleted = false,
                            JobRole = "Media",
                            LastName = "Evans",
                            MiddleName = "Beauty",
                            ModifiedBy = "HR",
                            PhoneNumber = "07027544487",
                            State = "Lagos",
                            WagesInDollar = 2500.0
                        },
                        new
                        {
                            Id = new Guid("7713bf21-9e81-4949-abf7-d5a64f281d69"),
                            Address = "30 Alpha estate lekki",
                            City = "Ikeja",
                            CreatedBy = "HR",
                            DeletedBy = "HR",
                            DepartmentId = new Guid("6c7e9c5d-89ae-43d9-8f19-feb71af65e8f"),
                            Email = "Adex@company.com",
                            FirstName = "Michael",
                            IsDeleted = false,
                            JobRole = "Media Lead",
                            LastName = "Adex",
                            ModifiedBy = "HR",
                            PhoneNumber = "0907794487",
                            State = "Lagos",
                            WagesInDollar = 5500.0
                        });
                });

            modelBuilder.Entity("CompanyData.Shared.Models.Employee", b =>
                {
                    b.HasOne("CompanyData.Shared.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
